name: Push Inventaire Excel

on:
  workflow_dispatch:  # Permet de lancer manuellement le workflow depuis GitHub

jobs:
  update-inventory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl

      - name: Update inventaire_global.xlsx
        run: |
          python update_inventaire.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add inventaire_global.xlsx
          git commit -m "Mise à jour automatique de inventaire_global.xlsx"
          git push
        env:
          # Le token est automatiquement disponible dans GitHub Actions en tant que GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
